import type {NextPage} from 'next'
import Head from 'next/head'
import Base from "../components/base/Base";
import {AboutMe, ContactMe, Curriculum, Hobbies} from "../components/pages/IndexPart";
import {getHobbies, Hobby} from "../posts";

export async function getStaticProps() {

    const hobbies = await getHobbies()

    return {
        props: {
            hobbies
        }
    }
}

interface HomeProps {
    hobbies: Hobby[]
}

const Home: NextPage<HomeProps> = ({hobbies}) => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Base>
                <>
                    <AboutMe/>
                    <Hobbies hobbies={hobbies}/>
                    <Curriculum/>
                    <ContactMe/>
                </>
            </Base>

        </>
    )
}

export default Home


